name = "9to5"
main = "dist/_worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
  command = "npm run build"

[[d1_databases]]
  binding = "DB"
  database_name = "9to5-frontend"
  database_id = "b5bc0929-de67-4982-a767-3847375b0d8b"

[[kv_namespaces]]
  binding = "SESSION"
  id = "df5aa39254fd4905a2f0e035f2d6a0c2"
  preview_id = "REPLACE_WITH_DEV_KV_ID"